<?php

namespace app\models;

use Yii;

/**
 * @property integer $id
 * @property integer $author_id
 * @property string $msg
 */
class Message extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['author_id','msg'],'required'],
            ['msg','string'],
            ['id','integer']
        ];
    }
}