<?php

namespace app\models;

use Yii;

/**
 * @property integer $id
 * @property integer $post_id
 * @property integer $author_id
 * @property string $reply
 * @property Post $post
 */
class Reply extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['reply'],'required'],
            ['reply','string'],
            [['id','author_id','post_id'],'integer'],
            ['author_id','safe']
        ];
    }

    public function beforeSave($insert)
    {
        $this->author_id = Yii::$app->user->getId();
        return parent::beforeSave($insert);
    }

    public function getPost()
    {
        return $this->hasOne(Post::class,['id'=>'post_id']);
    }
}